### ISSUE TITLE
Bad default bitraverse

### ISSUE THREAD

**Issue by phadej** [ekmett/bifunctors#102]
is it worth backporting?

https://github.com/haskell/core-libraries-committee/issues/47#issuecomment-1055634151

**Comment by RyanGlScott** [comment]
I think backporting that change would be worthwhile. The default implementation is so broken that I can't imagine anyone being heartbroken about its removal.

**Comment by phadej** [comment]
I think it won't even need a major release as we'd replace one bottom with more obvious one.

**Comment by RyanGlScott** [comment]
See #103.

**Comment by phadej** [comment]
Can this be closed, or is there something left?

**Comment by RyanGlScott** [comment]
Yes, I simply forgot to write "fixes #102" in the commit message. Thanks for the reminder!
