### ISSUE TITLE
bifunctor-classes-compat and old bifunctors

### ISSUE THREAD

**Issue by phadej** [ekmett/bifunctors#114]
It's easy to have an install plan with old `bifunctors` and (new) `bifunctor-classes-compat` thus having two `Bifunctor` definitions lying around for GHC-8.0 and older.

I don't recall how we have dealt with such issues previously, or did we at all?

EDIT: real world example:

Imagine I change [`assoc`](https://hackage.haskell.org/package/assoc) to depend on `bifunctor-classes-compat`: every current user of it (e.g. `these`) will break, as `these` would define `Bifunctor These` for `bifunctors.Bifunctor`.

Does this mean, that to do that change in `assoc`, I should make a major version bump, so the downstream would need to react? I guess so, unless there's some trick which escapes me now.

**Comment by phadej** [comment]
I'm fine with that. We probably should mention that in the changelog for upcoming `bifunctors` version.

**Comment by RyanGlScott** [comment]
I've amended the changelog in #115. Let me know if this is to your liking.
