### ISSUE TITLE
Depend on assoc for instances

### ISSUE THREAD

**Issue by phadej** [ekmett/bifunctors#120]
`assoc` provides `Bifunctor p => Swap p` and `Assoc p`  type-classes. 

Currently `assoc` depends on `bifunctors` to provide instances for `Flip`, `Biff` etc types defined in `bifunctors`.

But now we have a light compatibility package `bifunctor-classes-compat`.

So I propose a following dependency rearrangement:

- `assoc` depends on `bifunctor-classes-compat` and provides type-classes and instances for things in `base`
- `bifunctors` depends on `assoc` to provide `Swap` and `Assoc` instances for extra bifunctors defined here
- e.g. `lens` is not really affected, as it still depends on both `assoc` and `bifunctors`. `lens` defines `Wrapped` instance for `Biff`, `Clown` ... etc, otherwise it could drop (at least direct) `bifunctors` dependency as well)
- but e.g. `these` could drop `bifunctors` dependency as it only needs `Bifunctor` type-class and type-classes defined in `assoc` package.

This will be breaking change in `assoc` but only a minor change in `bifunctors`.

How does this sound?

**Comment by RyanGlScott** [comment]
That sounds reasonable to me. Are you willing to help migrating the instances?

**Comment by phadej** [comment]
Sure. I'll prepare a patch shortly

**Comment by phadej** [comment]
Done in #121
