### ISSUE TITLE
Make semigroupoids depend on bifunctors, not the other way around

### ISSUE THREAD

**Issue by RyanGlScott** [ekmett/bifunctors#20]
This is a bit of an unusual request, but would it be feasible to remove `bifunctors`' dependency on `semigroupoids` and move the affected instances to `semigroupoids` instead? The reason I want this is because as of GHC 7.10, `Data.Bifunctor` is in `base`, so anyone who wants to backport `Bifunctor` support for older versions of GHC will need to depend on `bifunctors`. This brings in a whole host of unneeded dependencies (e.g., `contravariant`, `StateVar`, `distributive`, etc.) just to be able to use `Data.Bifunctor`. Reversing the order of the dependencies would lighten the installation burden for users of older versions of GHC.

**Comment by RyanGlScott** [comment]
`bifunctors`' other dependencies (`tagged` and `semigroups`) I don't have much of a problem with, since `Data.Proxy` from `tagged` is already in `base`, and `Data.Semigroup` from `semigroups` is likely to become a part of `base` one day :)

**Comment by ekmett** [comment]
It is distinctly possible, but will require a lot of shuffling on my part.

(Every time I do one of these inversions I'm basically committing to a 50 hour binge.)

**Comment by RyanGlScott** [comment]
Hm, one thing I didn't realize originally was the `Biff`, `Clown`, `Joker`, and `Tannen` have instances for `Biapply`, `Bifoldable1`, and `Bitraversable1` in terms of `Apply`, `Foldable1`, and `Traversable1` from `semigroupoids`, making the relationship between `bifunctors` and `semigroupoids` more complicated than I imagined. In order invert the dependencies, that would require moving `Biapply`/`Bifoldable1`/`Bitraversable1` to `semigroupoids`, right? (Or some other module migration scheme?)

**Comment by ekmett** [comment]
Oh, that would appear to be the reason for the orientation of this dependency in the first place.

This may get downgraded to a "would be nice to have" issue.

**Comment by RyanGlScott** [comment]
The thing I'd really want above all else is the ability to backport `Bifunctor` back to earlier versions of GHC. At the moment, this can't be done with the `bifunctors` package, since it requires `base` ≥ 4.5 (and it depends on `semigroupoids`, which requires `base` ≥ 4.6).

Since we're already bikeshedding, what about the idea of splitting off `Data.Bifunctor` into its own Haskell98 package? (`bifunctors-core` or something catchy like that) That way, the extra `Biff`/`Clown`/`Joker`/`Tannen` functionality involving `semigroupoids` wouldn't have to be moved from the `bifunctors` package, which would (hopefully) minimize the heartburn involved in dependency inversion.

**Comment by ekmett** [comment]
My experience with splitting up packages into incredibly fine-grained components is that it doesn't end well for me, the maintainer.

It took me years to recover a fraction of the productivity I had before I splintered `category-extras` into pieces, and much of that ability to actually make progress again came from fusing together splintered packages. It netted me very few additional users, and complicated the story of where to get all the parts for _all_ of the users. I'm loathe to go in the opposite direction.

Previous versions of `semigroupoids` that are compatible with `bifunctors` work clear back to the stoneage, ghc-wise.

**Comment by ekmett** [comment]
An alternate suggestion would be to move `Bifoldable1`, and `Bitraversable1` to semigroupoids, then we might have a chance of making the inversion smoothly.

**Comment by RyanGlScott** [comment]
You're right, it's probably not a good idea to throw another package into the `category-extras` diaspora.

I wonder, though: if `semigroupoids` were removed as a dependency, would the current version of `bifunctors` be able to be built on versions of `base` prior to 4.5? I ask because currently, [`Data.Bifunctor` from `base`](http://hackage.haskell.org/package/base-4.8.0.0/docs/Data-Bifunctor.html) exports `Bifunctor ((,,,,,) x1 x2 x3 x4)` and `Bifunctor ((,,,,,,) x1 x2 x3 x4 x5)`, whereas [`Data.Bifunctor` from `bifunctors`](http://hackage.haskell.org/package/bifunctors-4.2.1/docs/Data-Bifunctor.html) does not. I'd like to add those instances to have parity between the two packages, but adding them at the moment doesn't feel like it would accomplish much if they could only be used on GHC 7.6+.

**Comment by ekmett** [comment]
I have no objection to adding those instances here. Toss together a pull request I guess.

**Comment by ekmett** [comment]
I've finished the easy (bifunctors) side of the inversion.

**Comment by ekmett** [comment]
Ok. instances added. Everything here looks good to me. Closing this issue. We probably will need to track things from the `semigroupoids` side as that half of the inversion is more complicated.

**Comment by RyanGlScott** [comment]
Awesome! Thanks a bunch for putting up with my numerous requests :)

**Comment by ekmett** [comment]
Happier to have users and requests than to have neither. ;)
