### ISSUE TITLE
Consolidation?

### ISSUE THREAD

**Issue by ekmett** [ekmett/bifunctors#30]
Adding `BifunctorComonad` carries a price. We don't have a good place to put the `BifunctorComonad` instance for `Tannen` it'd have to live as an orphan in `comonad` or cause us to pick up a `comonad` dependency.

On the other hand we have a `Cayley` construction in `profunctors`, which does exactly the same thing and works just fine because `profunctors` has a `comonad` dependency.

We could add a `comonad` dependency to this package, which might cause some hue and cry over the fact that `Data.Bifunctor` moved into base.

Or we could try to consolidate more of these little packages into a bigger package and kill the issue with cycles, and avoid orphan instances all in one go.

The issue is that in the `profunctors` world the free/cofree versions of each construction really should live with the class in question as they are always available, while here, we have a bit more freedom.

**Comment by RyanGlScott** [comment]
I think this issue might be moot nowadays, since `bifunctors` now depends on `comonad`.

**Comment by RyanGlScott** [comment]
This appears to have been resolved now that `Data.Bifunctor.Functor.BifunctorComonad` is in `bifunctors`, `Tannen` instance and all.
