### ISSUE TITLE
Type-level Uncurry?

### ISSUE THREAD

**Issue by duairc** [ekmett/bifunctors#31]
I'm writing some code and I've run into the need to have a type like this:

``` haskell
newtype Uncurry f (p :: (k, l)) = Uncurry (forall a b. p ~ '(,) a b => f a b)
```

I've tried to see if there exists a type like that in any popular packages, but there doesn't seem to be. There may be under a different name though. But assuming there isn't, would you be interested in adding such a type to `bifunctors`? It seems like a reasonable place to put such a type. If you're interested, I can do up a pull request with appropriate instances and everything. If you have some guidance about what module you'd like to put it in (i.e., what you'd call that module) that would help too, because I'm not really sure what to call it. Thanks!

**Comment by duairc** [comment]
Okay, so it turns out that that `newtype` is useless, but if you make it a GADT it's good. I've done that in #37. I still don't know if you're interested in it, but I've done up a pull request anyway and if you're not I can just use it in my own code, but it seems like the kind of thing that would be reusable and it sort of fits in `bifunctors`.

**Comment by ekmett** [comment]
Closing per the commentary on #37.
