### ISSUE TITLE
GHC-8.0 compatibility regarding template-haskell

### ISSUE THREAD

**Issue by amigalemming** [ekmett/bifunctors#39]
ghc-8.0.0.20160109 says:
~~~~
[ 1 of 15] Compiling Paths_bifunctors ( dist/build/autogen/Paths_bifunctors.hs, dist/build/Paths_bifunctors.o )
[ 2 of 15] Compiling Data.Bifunctor.TH.Internal ( src/Data/Bifunctor/TH/Internal.hs, dist/build/Data/Bifunctor/TH/Internal.o )

src/Data/Bifunctor/TH/Internal.hs:221:19: error:
    Not in scope: data constructor ‘FamilyD’
    Perhaps you meant ‘FamilyI’ (imported from Language.Haskell.TH.Syntax)
~~~~

**Comment by RyanGlScott** [comment]
Working on it :)

**Comment by phadej** [comment]
I tried current `master`, it compiled nicely for me.

**Comment by RyanGlScott** [comment]
Well, `master` does compile, but the Template Haskell–related code is still a mess for various reasons, including (but not limited to):

1. GHC 8.0 changes the way TH represents GADTs, so `deriveBifoldable` won't work on GADTs at the moment
2. There are many more possible data types that can be defined due to `-XTypeInType`, which the current code doesn't consider

So the non-TH code works, but I'll need to rewrite a bunch of `Data.Bifunctor.TH` to get everything up-to-speed.

**Comment by amigalemming** [comment]
On Wed, 13 Jan 2016, Ryan Scott wrote:

> So the non-TH code works, but I'll need to rewrite a bunch of 
> Data.Bifunctor.TH to get everything up-to-speed.

I do not use Template Haskell, thus at least for me this part is not 
urgent.

**Comment by phadej** [comment]
@amigalemming optionally if you need only `Bifunctor` class and don't need to support older GHC (<7.10), then `Bifunctor` it's already in `base`.

**Comment by phadej** [comment]
@RyanGlScott IMHO supporting new data types (your second point) is not worth holding the release. The first one is.

Anyway, thanks for working on this. :+1:

**Comment by RyanGlScott** [comment]
My hope is to due some GHC 8.0–related power-coding this weekend, and this is high on the agenda. The hardest part is that I have to write a mini-typechecker in TH to ensure that you actually pass something of kind `* -> * -> *` (and that's tricker than ever thanks to kind equalities), while working around several old TH bugs... If I can get that working, the rest shouldn't be too bad.

**Comment by RyanGlScott** [comment]
I've rewritten `Data.Bifunctor.TH` in b032dd2378a565e8e61c7e5377c9201fad33eb06, and now it should compile warning-free in GHC 8.0.

@ekmett, I've bumped the version number to 5.2.1. Pending a successful build on Travis, can you release a new version to Hackage? I believe deriving `Bifoldable` for GADTs is currently broken.

**Comment by ekmett** [comment]
Sure.

**Comment by ekmett** [comment]
Shipped.
