### ISSUE TITLE
Haddock failure in stackage nightly build

### ISSUE THREAD

**Issue by bergmark** [ekmett/bifunctors#42]
```
src/Data/Bifunctor/TH.hs:675:5:
    parse error on input ‘-- * after substituting * for the dropped kind variables. If not, throw an error.’
```

**Comment by RyanGlScott** [comment]
00b941f126852754ecb4b4150829011f245347d5 fixes this - we just need a new `bifunctors` Hackage release.

**Comment by slpopejoy** [comment]
Note this also broke docs on hackage, a new release would be grand.

**Comment by lehins** [comment]
I also get this error with ghc-7.8.4

    Preprocessing library bifunctors-5.2.1...
    
    src/Data/Bifunctor/TH.hs:611:19:
        parse error on input ‘-- ^ Note that due to a GHC 7.8-specific bug
                      --   (see Note [Polykinded data families in Template Haskell]),
                      --   there may be more kind variable names than there are kinds
                      --   to substitute. But this is OK! If a kind is eta-reduced, it
                      --   means that is was not instantiated to something more specific,
                      --   so we need not substitute it. Using stealKindForType will
                      --   grab the correct kind.’

**Comment by RyanGlScott** [comment]
I just uploaded [`bifunctors-5.3`](http://hackage.haskell.org/package/bifunctors-5.3), which should fix this issue (I made sure to run `cabal haddock` beforehand to be sure). Please reopen if the issue persists.

**Comment by bergmark** [comment]
Thanks! Stack is still using an older version due to https://github.com/fpco/stackage/issues/1266
