### ISSUE TITLE
Bitraverse laws bug

### ISSUE THREAD

**Issue by adelbertc** [ekmett/bifunctors#43]
It looks like on https://github.com/ekmett/bifunctors/commit/391c3142c9c515c73d12a330e42e35768feddeb4#L283 there's a `t .` missing on the right hand side of that law.

[Hackage](https://hackage.haskell.org/package/bifunctors-4.2.1/docs/Data-Bitraversable.html) says

> naturality
> `bitraverse (t . f) (t . g) ≡ t . bitraverse f g for every applicative transformation t`

**Comment by RyanGlScott** [comment]
> `bitraverse (t . f) (t . g) ≡ t . bitraverse f g`

That looks correct to me. What do you think it should be?

**Comment by adelbertc** [comment]
@RyanGlScott The Hackage looks good to me, but the [code](https://github.com/ekmett/bifunctors/commit/391c3142c9c515c73d12a330e42e35768feddeb4#L283) looks like it's missing `t` on the right hand side

**Comment by RyanGlScott** [comment]
What "code" are you referring to? The [link](https://github.com/ekmett/bifunctors/commit/391c3142c9c515c73d12a330e42e35768feddeb4#L283) you gave does not point to a particular line of code.

**Comment by adelbertc** [comment]
Oh that's strange.. how about this one? https://github.com/ekmett/bifunctors/blob/391c3142c9c515c73d12a330e42e35768feddeb4/tests/BifunctorSpec.hs#L283

**Comment by RyanGlScott** [comment]
Good catch. I've updated the test suite to properly test this law.
