### ISSUE TITLE
Add functions to focus on each side of a BiFoldable

### ISSUE THREAD

**Issue by treeowl** [ekmett/bifunctors#48]
```haskell
foldMapLefts :: (Bifoldable f, Monoid m)
    => (a -> m) -> f a b -> m
foldMapLefts f = bifoldMap f (const mempty)
```

Etc., etc.

**Comment by RyanGlScott** [comment]
I have to wonder if this meets the Fairbairn threshold—there are a _lot_ of variations on `bifoldr` and `bifoldMap` in `Data.Bifoldable`, and for each one, you could conceivably make two more combinators out of it by passing `flip const` or `const mempty` as one of the arguments.

**Comment by RyanGlScott** [comment]
Also, `Bifoldable` is in `base` now, so any proposals for new functions in `Data.Bifoldable` should probably go through GHC Trac / the Core Libraries Committee.

**Comment by treeowl** [comment]
@RyanGlScott, I think your point about all the other potential functions is a good one. I'll close this issue.
