### ISSUE TITLE
bifunctors-5.4 contains breaking change

### ISSUE THREAD

**Issue by hvr** [ekmett/bifunctors#51]
@phadej discovered this via https://github.com/ekmett/pointed/issues/17#issuecomment-233589998

There's two options from here on:

 - A) Follow-up quickly with a `bifunctors-5.4.0.1` release which fixes this by marking the affected modules trustworthy and restore their previous SafeHaskell status (and then declare `bifunctors-5.4` a broken release)

or the more messy

 - B) Consider this a desired breaking change and keep those modules unsafe, which means retrofitting `bifunctors < 5.4` upper bounds in some places.

**Comment by phadej** [comment]
:+1: for option A, and marking `bifunctors-5.4` broken by adding `base<0` dependency.

**Comment by RyanGlScott** [comment]
Well, this is unintentional disaster.

Here's my plan:

1. Once #52 validates, merge that and release `bifunctors-5.4.1` to Hackage.
2. Mark `bifunctors-5.4` as deprecated on Hackage. (I don't _think_ we need to mark it as broken, since it still technically compiles, but speak up if I'm wrong about this.)

Any objections?

**Comment by RyanGlScott** [comment]
For the `base` changes, see https://phabricator.haskell.org/D2412.

**Comment by phadej** [comment]
@RyanGlScott technically no, as major bump to `5.4` makes you able to introduce breaking change (which making stuff not-safe kind-of-was). But if don't mark `bifunctors-5.4` as broken, and go with  `5.4.1`, then you'd need to adjust all dependencies which depend on safeness with something like `bifunctors >= 5 && <5.4 && bifunctors >=5.4.1 && <6`. Even we know that it's highly *unluckily* for solver to pick `bifunctors-5.4` when `bifunctors-5.4.1` exists, it's *possible*.

It's better not to have any possibilities to have unbuildable install-plans. Also `bifunctors-5.4` haven't yet made into any stackage snapshot, so if you make `5.4.0.1` today, everything would like `bifunctors-5.4` never existed.

**Comment by RyanGlScott** [comment]
I'm not sure I follow what you're saying about the version numbers—going from `5.4` to `5.4.1` isn't a major version bump according to the PVP, correct? I choose not to bump quaternary version numbers unless it's an extremely minor, non-code-facing change (like a documentation fix).

**Comment by phadej** [comment]
@RyanGlScott, I guess @hvr proposal for `bifunctors-5.4.0.1` (and marking `5.4` as broken) is to pretend that `bifunctors-5.4` was clear mistake which shouldn't have ever happened. I'm sure you wouldn't release it in the first place, if you tried to build the rest of "ekmett-universe" (up to `pointed`) with it.

**Comment by RyanGlScott** [comment]
Sure, I'm fine with marking `bifunctors-5.4` as broken. But I'm still confused about your distinction between releasing `bifunctors-5.4.0.1` and `bifunctors-5.4.1`. I'm arguing the latter is necessary due to the code-related changes required to fix the issue in `5.4`—is this not the case?

**Comment by phadej** [comment]
@RyanGlScott, if `bifunctors-5.4` isn't installable (with `base<0` revision), then it's the same, if it's `5.4.1` or `5.4.0.1`.

**Comment by RyanGlScott** [comment]
Very well, I've uploaded [`bifunctors-5.4.1`](http://hackage.haskell.org/package/bifunctors-5.4.1) to Hackage, and have made `bifunctors-5.4` unbuildable (as well as deprecated, for good measure).
