### ISSUE TITLE
(Bi?)Compose 

### ISSUE THREAD

**Issue by Icelandjack** [ekmett/bifunctors#57]
Section **3** of [*Constructing Applicative Functors*](http://www.staff.city.ac.uk/~ross/papers/Constructors.pdf) describes defining `ZipList` as a fixed point of the composition of `Maybe ∘ ×`. If we have a composition of a functor and a bifunctor

```haskell
newtype (f · g) a b = C (f (g a b))
```

we can define `ZipList` as `Fix (Maybe · (,))`

```haskell
type ZipList = Fix (Maybe · (,))

pattern Nil :: ZipList a
pattern Nil = In (C Nothing)

infixr 5 :::
pattern (:::) :: a -> ZipList a -> ZipList a
pattern a:::as = In (C (Just (as, a)))
```

**Comment by RyanGlScott** [comment]
Isn't this what [`Tannen`](https://github.com/ekmett/bifunctors/blob/9972e950069de5e3b5d740eea0752657fbc463d1/src/Data/Bifunctor/Tannen.hs#L66) gives you?

```haskell
newtype Tannen f p a b = Tannen { runTannen :: f (p a b) }
type (·) = Tannen
```

**Comment by Icelandjack** [comment]
Not surprised this existed already but the name is not very descriptive

**Comment by Icelandjack** [comment]
I'll use this instead and close the ticket :) thanks
