### ISSUE TITLE
bisequence

### ISSUE THREAD

**Issue by Icelandjack** [ekmett/bifunctors#59]
From [here](https://github.com/tomjaguarpaw/solver-example/blob/d9fa46a258a1543a206f1346447c109928f98ffb/Bisequence.hs), I don't know if it requires unsafe

```haskell
biSequence :: (Biapplicative p, T.Traversable t) => t (p a b) -> p (t a) (t b)
biSequence = bimap (fmap somethingCoerce) (fmap somethingCoerce)
             . unCollapse
             . T.sequenceA
             . fmap (Collapse . bimap Something Something)
```

**Comment by RyanGlScott** [comment]
At the very least, I'd like to see an implementation of this that doesn't use `unsafeCoerce`.

**Comment by treeowl** [comment]
I don't we should call this `bisequence`, because it's very different from `bitraverse`. Should we call it `disequence`, or would that evoke `Profunctor` too strongly?

**Comment by treeowl** [comment]
@Icelandjack, see #69.
